spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecom
    username: root
    password: 123456a@
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: false
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        
jwt:
  serectKey: ecomApp